[package]
name = "mfx"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = [
    "time",
    "i2c",
] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
ariel-os-stm32 = { path = "../../src/ariel-os-stm32", features = ["usb-host"] }
embedded-hal-async = "1.0"

[lints]
workspace = true
